# Generated by Django 5.2.9 on 2025-12-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_share',
            field=models.ImageField(blank=True, null=True, upload_to='posts_share/'),
        ),
    ]
