"""
Django settings for rede_social project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*8l^hcoxbtynxk9wvib3ph^08$)bip$w(m98@$vi3(23g9_#3n'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'usuarios',
    'mensagens',
    #'django_celery_beat',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.HandleGenericExceptionMiddleware',  
]

ROOT_URLCONF = 'rede_social.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.static',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'mensagens.context_processors.conversas_recebidas',
            ],
        },
    },
]

WSGI_APPLICATION = 'rede_social.wsgi.application'

ASGI_APPLICATION = 'rede_social.asgi.application' 

# Redis (necessário para gerenciar as conexões)
CHANNEL_LAYERS = {
    'default': {
       'BACKEND': 'channels_redis.core.RedisChannelLayer',
       'CONFIG': {
         'hosts': [("redis", 6379)], # << deve bater com o nome do serviço docker
        },
    },
}

'''
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'rede_loja'),
        'USER': os.getenv('DB_USER', 'clebertjw'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'redeloja'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Configuração Redis (se for usar caching ou Celery)
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
REDIS_PORT = os.getenv('REDIS_PORT', 6379)

# Segurança mínima para produção
DEBUG = False
ALLOWED_HOSTS = ['*']  # Para testes locais, ajustar para o domínio real em produção
# ⚠️ Em produção real, nunca use ALLOWED_HOSTS=['*']. Aqui é só para teste local via Docker.

'''
# uso local para teste
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.1.12',   # IP local da sua máquina
    '0.0.0.0'         # aceita conexões em qualquer IP local
]

DEBUG = True
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # 'db_data' /

    }
}
 
# Configuração Redis (se for usar caching ou Celery)
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
REDIS_PORT = os.getenv('REDIS_PORT', 6379)


# SITE_URL = "https://seudominio.com"
# Ou deixe genérico para ambiente dev:

# Copiar código
SITE_URL = "http://localhost:8000"


'''uso local '''
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

'''uso Docker 
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"

CELERY_TIMEZONE = 'America/Sao_Paulo'
'''
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# https://docs.djangoproject.com/en/5.2/howto/static-files/
# URL base para acessar os arquivos estáticos.
STATIC_URL = '/static/' 
# Diretório onde os arquivos estáticos serão coletados

# ===============================
# 🎨 Arquivos Estáticos (CSS, JS, imagens do sistema)
# ===============================

# Diretórios adicionais de arquivos estáticos do projeto.
# Estes são arquivos fixos (não enviados por usuários).
# Usados durante o desenvolvimento.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# quando o comando `collectstatic` for executado.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===============================
# 🔐 Configurações de Autenticação
# ===============================

# Após o login bem-sucedido, o usuário será redirecionado
# para a URL nomeada 'home' (definida no urls.py).
LOGIN_REDIRECT_URL = 'home'

# Página padrão de login do sistema.
# Se uma view exigir autenticação e o usuário não estiver logado,
# ele será enviado para essa rota.
LOGIN_URL = 'login'

# Após o logout, o usuário será redirecionado para a página de index ou home, depende da rota.
LOGOUT_REDIRECT_URL = 'home'


# ===============================
# 📂 Configurações de Arquivos de Mídia (uploads de usuários)
# ===============================

# URL base para acessar os arquivos enviados pelos usuários (uploads).
# Exemplo: /media/fotos/perfil.jpg
MEDIA_URL = '/media/'

# Caminho físico dentro do projeto onde os arquivos de mídia
# serão armazenados. Pasta: BASE_DIR/media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Diretório onde os arquivos estáticos serão coletados# Configurações de mensagens

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}
# ===============================
# Configurações de E-mail (Gmail SMTP)
# ===============================
# Configurações para enviar e-mails usando o Gmail SMTP.
# para produção troque console, por smtp
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
DEFAULT_FROM_EMAIL = 'LabySim <tec.tjw@gmail.com>'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True # Use TLS para segurança 
EMAIL_HOST_USER = 'tec.tjw@gmail.com' # Coloque seu e-mail do Gmail aqui
EMAIL_HOST_PASSWORD = 'bsxt uase xiub mfic'  # Use uma senha de app do Gmail


WHATSAPP_TOKEN = 'EAALol6BRH58BQKceopGZApg7OEdcXKJSsmbNUMaLuZChp2AtwINuklYMMoIHWOrvgZAYfwSQH23ywlST1YKcWfsBeIlGjR5EkAvfwRxbroPjJjK1xTin0Qao5ZB2fu8R6yeweBSijsW9KwFL9OrPIQsYlMw0y5L4tPVGUZBmSm0slrq0hOTPbOBGnFlhLuUDHUdZANhDqo6ZBaBYbVedEyXi96WcdMzBQWPHB3nc7vX3Ak71QrpkfXZB9mSgyLlJBVZATVsdBhYA5FMryGLZAbGopFHbxfux9V6WdsILYFzBwZD'  # SEU token de acesso da Meta
WHATSAPP_PHONE_NUMBER_ID = '15556014671'  # ID fornecido pela Meta


# ===============================
# 📂 Configurações de Arquivos de Mídia (uploads de usuários
# ===============================
# URL base para acessar os arquivos enviados pelos usuários (uploads).
# Exemplo: /media/fotos/perfil.jpg      

SECURE_CROSS_ORIGIN_OPENER_POLICY = None
# Caminho físico dentro do projeto onde os arquivos de mídia
