"""
Django settings for rede_social project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*8l^hcoxbtynxk9wvib3ph^08$)bip$w(m98@$vi3(23g9_#3n'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'usuarios',
    'mensagens',
    #'django_celery_beat',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.HandleGenericExceptionMiddleware',  
]

ROOT_URLCONF = 'rede_social.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.static',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'mensagens.context_processors.conversas_recebidas',
            ],
        },
    },
]

WSGI_APPLICATION = 'rede_social.wsgi.application'

ASGI_APPLICATION = 'rede_social.asgi.application' 

# Redis (necessário para gerenciar as conexões)
CHANNEL_LAYERS = {
    'default': {
       'BACKEND': 'channels_redis.core.RedisChannelLayer',
       'CONFIG': {
         'hosts': [("redis", 6379)], # << deve bater com o nome do serviço docker
        },
    },
}

from decouple import config

SECRET_KEY = config('SECRET_KEY')
'''
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Redis (opcional)
REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', cast=int, default=6379)
'''

# E-mail
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')


# WhatsApp
WHATSAPP_TOKEN = config('WHATSAPP_TOKEN')
WHATSAPP_PHONE_NUMBER_ID = config('WHATSAPP_PHONE_NUMBER_ID')
WHATSAPP_BUSINESS_ACCOUNT_ID = config('WHATSAPP_BUSINESS_ACCOUNT_ID')
# Configurações para

# uso local para teste
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '192.168.1.12',   # IP local da sua máquina
    '0.0.0.0'         # aceita conexões em qualquer IP local
]

DEBUG = True
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3', # 'db_data' /

    }
}
 
# Configuração Redis (se for usar caching ou Celery)
REDIS_HOST = os.getenv('REDIS_HOST', 'redis')
REDIS_PORT = os.getenv('REDIS_PORT', 6379)


# SITE_URL = "https://seudominio.com"
# Ou deixe genérico para ambiente dev:

# Copiar código
SITE_URL = "http://localhost:8000"


'''uso local '''
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

'''uso Docker 
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"

CELERY_TIMEZONE = 'America/Sao_Paulo'
'''
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# https://docs.djangoproject.com/en/5.2/howto/static-files/
# URL base para acessar os arquivos estáticos.
STATIC_URL = '/static/' 
# Diretório onde os arquivos estáticos serão coletados

# ===============================
# 🎨 Arquivos Estáticos (CSS, JS, imagens do sistema)
# ===============================

# Diretórios adicionais de arquivos estáticos do projeto.
# Estes são arquivos fixos (não enviados por usuários).
# Usados durante o desenvolvimento.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
# quando o comando `collectstatic` for executado.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ===============================
# 🔐 Configurações de Autenticação
# ===============================

# Após o login bem-sucedido, o usuário será redirecionado
# para a URL nomeada 'home' (definida no urls.py).
LOGIN_REDIRECT_URL = 'home'

# Página padrão de login do sistema.
# Se uma view exigir autenticação e o usuário não estiver logado,
# ele será enviado para essa rota.
LOGIN_URL = 'login'

# Após o logout, o usuário será redirecionado para a página de index ou home, depende da rota.
LOGOUT_REDIRECT_URL = 'home'


# ===============================
# 📂 Configurações de Arquivos de Mídia (uploads de usuários)
# ===============================

# URL base para acessar os arquivos enviados pelos usuários (uploads).
# Exemplo: /media/fotos/perfil.jpg
MEDIA_URL = '/media/'

# Caminho físico dentro do projeto onde os arquivos de mídia
# serão armazenados. Pasta: BASE_DIR/media
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Diretório onde os arquivos estáticos serão coletados# Configurações de mensagens

MESSAGE_TAGS = {
    messages.DEBUG: 'alert-info',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


# ===============================
# 📂 Configurações de Arquivos de Mídia (uploads de usuários
# ===============================
# URL base para acessar os arquivos enviados pelos usuários (uploads).
# Exemplo: /media/fotos/perfil.jpg      

SECURE_CROSS_ORIGIN_OPENER_POLICY = None
# Caminho físico dentro do projeto onde os arquivos de mídia
