# Generated by Django 5.2.7 on 2025-11-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do template', max_length=100)),
                ('tipo', models.CharField(choices=[('confirmacao', 'Confirmação de agendamento'), ('lembrete', 'Lembrete de atendimento'), ('avaliacao', 'Solicitação de avaliação'), ('pagamento', 'Pagamento pendente'), ('personalizado', 'Personalizado')], max_length=20)),
                ('conteudo', models.TextField(help_text='Mensagem com placeholders, ex: {cliente}, {profissional}, {data}, {hora}')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
