# Generated by Django 5.2.7 on 2025-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospessoais',
            name='endereco',
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='email_recuperacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Email para recuperar conta'),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, verbose_name='Numero'),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='rua',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rua'),
        ),
    ]
